source 'https://rubygems.org'

# PacketHost dependencies
gem 'faraday',             '~> 0.15'
gem 'faraday_middleware',  '~> 0.12'
gem 'activesupport',       '~> 4.2'
gem 'i18n',                '~> 0.9'

gem 'highline',            '~> 1.7'
