.TH "ONEPROVISION" 1 "June 2018" "oneprovision" "oneprovision(1) -- provisioning tool"
.SH NAME
oneprovision \- OpenNebula Provisioning Tool
.SH SYNOPSIS
oneprovision [options]
.SH DESCRIPTION
oneprovision tool allows to easily add new computing resources from public bare metal cloud provides into the OpenNebula.
.SH OPTIONS
Use oneprovision --help to get available commands and options.
.SH AUTHOR
Copyright 2002\-2018, OpenNebula Project, OpenNebula Systems
